### PR TITLE
better log

### PR DESCRIPTION
**Pull request by sbcgua**
to #247 plus some docs

Regular log reduced to 
image

verbose log can be initiated either by `-v` arg or `VERBOSE=1` in `.env` file in the package root
image

@ed-holland does it look better ?

### CODE REVIEW

**Comment by ed-holland** [comment]
> to #247 plus some docs
> 
> Regular log reduced to
> image
> 
> verbose log can be initiated either by `-v` arg or `VERBOSE=1` in `.env` file in the package root
> image
> 
> @ed-holland does it look better ?

It sure shows what is done for whom. I'm running the sci-server using the docker image. I was not aware there is an .env file in the package root.

**Comment by sbcgua** [comment]
@ed-holland `.env` is a very common mechanism - https://github.com/motdotla/dotenv - and convenient too. But might be not for docker. At least not in the way it is built now - `.env` is not included for security reasons. But custom builds for sure can include one. 

For the "official" docker image it is better to pass env vars in the command line e.g.
`docker run ... --env VERBOSE=1` - https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

**Comment by ed-holland** [comment]
Thanks for the explanation. Adding verbose to the docker image using Portainer is easy. I'll wait for the merge to be able to test.

**Comment by sbcgua** [comment]
fixed. I have no idea how it worked before, it was a bit in a mess in a couple of places. #96 is next ...

P.S. @larshp do you mind if I add index.js to the root? Just calling `import src/server`. It will make scripts cleaner. (it will be separately, probably within #96)

**Comment by larshp** [comment]
moving index.js: no problem

thanks, merging

**Pull request merged**
